### ISSUE TITLE
Improved console output and overall performance

### ISSUE THREAD

**Issue by Sedatif** [0rqheus/SEM_lab1#2]
Use Promise.all() to process createCities() and simulate() calls concurrently to improve the overall performance.
Utilize map() and join() functions for generating console output to simplify the console output generation.

https://github.com/0rqheus/SEM_lab1/blob/cb755923415b208b0a4fe870b63ad22caba21c2f/src/index.ts#L6-L18

**Comment by Sedatif** [comment]
But I'm not pushing for a change, as these are minor tweaks that don't improve the understanding of the already fairly optimized code very much.

**Comment by 0rqheus** [comment]
Yes, it won't get much performance difference for this case, so I think it's better for readability to leave it this way.
