### ISSUE TITLE
CountryParamsSchema.parse() issue

### ISSUE THREAD

**Issue by Sedatif** [0rqheus/SEM_lab1#6]
https://github.com/0rqheus/SEM_lab1/blob/cb755923415b208b0a4fe870b63ad22caba21c2f/src/services/cli.ts#L42-L47

maybe move `CountryParamsSchema.parse(data)`? We don`t need to parse data before checking.

**Comment by 0rqheus** [comment]
It's not parsing, it's a method of zod validation library. So it also performs a validation check.
